### ISSUE TITLE
Failed to install on Ubuntu 14.04 - Can't locate strict.pm 

### ISSUE THREAD

**Issue by knutov** [tokuhirom/Perl-Build#90] opened 2019-01-18 02:09 UTC
copy of https://github.com/tokuhirom/plenv/issues/153

Installing latest stable with `plenv`:

Ubuntu 14.04
system perl v5.18.2

doing `plenv install 5.28.1` and getting error about `strict.pm`. How to fix it?

```
...
/bin/ln -s perldelta.pod pod/perl5281delta.pod
./miniperl -Ilib autodoc.pl
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /cpan/AutoLoader/lib /dist/Carp/lib /dist/PathTools /dist/PathTools/lib /cpan/ExtUtils-Install/lib /cpan/ExtUtils-MakeMaker/lib /cpan/ExtUtils-Manifest/lib /cpan/File-Path/lib /ext/re /dist/Term-ReadLine/lib /dist/Exporter/lib /ext/File-Find/lib /cpan/Text-Tabs/lib /dist/constant/lib /cpan/version/lib /lib .) at autodoc.pl line 25.
BEGIN failed--compilation aborted at autodoc.pl line 25.
make: *** [pod/perlintern.pod] Error 2
Installation failure: make at /home/user/.plenv/plugins/perl-build/bin/perl-build line 10353.
ABORT
```

**Comment by skaji** [comment] 2019-01-18 13:19
* Which version do you use? `plenv install --version`
* Could you copy and paste the whole build log?

**Comment by knutov** [comment] 2019-01-18 15:55
```
$ plenv install --version
Use of uninitialized value $Perl::Build::VERSION in concatenation (.) or string at /home/kola/.plenv/plugins/perl-build/bin/plenv-install line 63.
```

I did fresh install of plenv from "Basic GitHub Checkout" from https://github.com/tokuhirom/plenv#installation

`plenv install 5.28.1 | tee plenv.log` [plenv.log](https://github.com/tokuhirom/Perl-Build/files/2773609/plenv.log)
`plenv install 5.28.1 2>&1 | tee plenv2.log` [plenv2.log](https://github.com/tokuhirom/Perl-Build/files/2773610/plenv2.log)

**Comment by skaji** [comment] 2019-01-18 17:03
@knutov Thanks for build logs.
I was not able to reproduce this issue.

Can you build perl if you do not use Perl::Build?
```sh
#!/bin/bash

wget https://cpan.metacpan.org/authors/id/S/SH/SHAY/perl-5.28.1.tar.gz
tar xzf perl-5.28.1.tar.gz
cd perl-5.28.1
./Configure -de -Dprefix=/tmp/test
make
```

**Comment by knutov** [comment] 2019-01-18 20:13
no, `make` ends with the same error.

**Comment by skaji** [comment] 2019-01-19 00:50
@knutov Thanks.

> no, make ends with the same error.

Then this is not an issue for perl-build nor plenv, but perl itself.

**Comment by skaji** [comment] 2019-01-20 02:37
Since this is not an issue for perl-build, I close this ticket.

**Closed by skaji** 2019-01-20 02:37 UTC
